port: load balancer port
strategy: round_robin | weighted_round_robin | least_connections | random
health_check_interval_seconds: 2
rate_limiter_enabled: true
rate_limit_tokens: 10
rate_limit_interval_seconds: 1
servers:
  - name: server1
    url: http://localhost:8080
    health_url: /health
    weight: 1
  - name: server2
    url: http://localhost:8082
    health_url: /health-check
    weight: 2
  - name: server3
    url: http://localhost:8083
    health_url: /healthcheck
    weight: 2
tls_enabled: true
tls_cert_file: /path/to/cert.pem
tls_key_file: /path/to/key.pem
